### Valid Request
POST http://127.0.0.1:5000/evaluate_move
Content-Type: application/json

{
  "fen": "r2qkbnr/pp3ppp/2np4/2p1pb2/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 1",
  "move": "b2b4"
}
### Missing FEN Field
POST http://127.0.0.1:5000/evaluate_move
Content-Type: application/json

{
  "fen": "r2qkbnr/pp3ppp/2np4/2p1pb2/3PP3/5N2/PPP2PPP/RNBQKB1R w KQkq - 0 1",
  "move": "e7e5"
}
### Missing Move Field
POST http://127.0.0.1:5000/evaluate_move
Content-Type: application/json

{
  "fen": "r1bqkbnr/pppppppp/2n5/8/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 2 2"
}
### Invalid FEN String
POST http://127.0.0.1:5000/evaluate_move
Content-Type: application/json

{
  "fen": "invalid_fen_string",
  "move": "e7e5"
}
### Invalid Move Notation
POST http://127.0.0.1:5000/evaluate_move
Content-Type: application/json

{
  "fen": "r1bqkbnr/pppppppp/2n5/8/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 2 2",
  "move": "Kb4"
}
### Empty Request Body
POST http://127.0.0.1:5000/evaluate_move
Content-Type: application/json

{}
### Non-JSON Content Type
POST http://127.0.0.1:5000/evaluate_move
Content-Type: text/plain

{
  "fen": "r1bqkbnr/pppppppp/2n5/8/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 2 2",
  "move": "e7e5"
}
