name: Run Tests on backend PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

env:
  LLM_API_KEY: ${{ secrets.SECRET_KEY }}
  STOCKFISH_EXECUTABLE: stockfish_binaries/stockfish-ubuntu-x86-64-avx2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd backend 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Stockfish
        run: |
          cd backend
          mkdir stockfish_binaries
          curl -L -o stockfish_binaries/stockfish.tar.gz https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-ubuntu-x86-64-avx2.tar
          tar -xf stockfish_binaries/stockfish.tar.gz --strip-components=1 -C stockfish_binaries
          chmod +x stockfish_binaries/stockfish-ubuntu-x86-64-avx2

      - name: Verify Stockfish executable
        run: |
          ls ./backend/stockfish_binaries
          ls -l ./backend/stockfish_binaries/stockfish-ubuntu-x86-64-avx2
          ./backend/stockfish_binaries/stockfish-ubuntu-x86-64-avx2 --version

      - name: Run Quart app
        run: |
          cd backend
          export QUART_APP=run:app
          nohup quart run --host 127.0.0.1 --port 5000 &

      - name: Wait for Quart to be ready
        run: |
          for i in {1..30}; do
            curl --silent http://127.0.0.1:5000/ && break
            echo "Waiting for Quart to start..."
            sleep 2
          done

      - name: Run tests
        run: |
          cd backend/test
          python test_runner.py
