name: Run Tests on backend PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

env:
  LLM_API_KEY: ${{ secrets.SECRET_KEY }}
  STOCKFISH_EXECUTABLE: stockfish/stockfish-ubuntu-x86-64-avx2
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd backend 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Stockfish
        run: |
          cd backend
          mkdir stockfish_binaries
          curl -L -o stockfish_binaries/stockfish.tar.gz https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-ubuntu-x86-64-avx2.tar
          tar -xf stockfish_binaries/stockfish.tar.gz --strip-components=1 -C stockfish_binaries
          mv stockfish_binaries/stockfish-ubuntu-x86-64-avx2 stockfish_binaries/stockfish-executable
          chmod +x stockfish_binaries/stockfish-executable
 

      - name: Run flask app
        run: |
          cd backend
          nohup python run.py &

      - name: Wait for Flask to be ready
        run: |
          for i in {1..30}; do
            curl --silent http://127.0.0.1:5000/ && break
            echo "Waiting for Flask to start..."
            sleep 2
          done

      - name: Run tests
        run: |
          cd backend
          python test_runner.py